### ISSUE TITLE
Re-work Institutional Titles list

### ISSUE THREAD

**Issue by iyawnis** [k-int/KBPlus#896] opened 2015-04-30 15:25 UTC
"The way this page is generated really needs an overhaul to improve performance and functionality but this may be a more substantial piece of work" 

Need specific description of what will be in the screen etc. 

spreadsheet: 241

**Comment by ostephens** [comment] 2015-05-05 09:38
OK - I think the main issue here is performance, so strictly improving performance should be the starting point of any work here.

_However_ I'm not sure if the performance issues are routed in the functionality the page is trying to deliver, or just problems with how it is implemented. Probably both!

So - we want to maintain the functionality overall, but it doesn't necessarily all have to be in the same page - e.g. I'd understood by a comment that @ianibbo that supporting the 'Titles we subscribe to through 2 or more packages' filter option maybe one of the causes of performance issues - so if moving this to a separate page/report gets us improvements to performance of this page, then I think that would make sense to do.

The overall functionality I think we need to maintain is:

List of all titles to which an institution has a subscription which can be filtered by:
- Date (i.e. see titles subscribed as of X date)
- Subscription
- Content Provider
- Platforms (host/other)

List should display:
- Title
- ISSN & eISSN
- Earliest coverage start date
- Latest coverage end date or 'to current'
- Listing each Subscription/IE in which the title appears for the institution

As noted previously, happy to see the 'Titles we subscribe to through 2 or more packages' option moved to a separate report, but this is still a desired piece of functionality.

Just a thought which came out of a discussion with @damyantipatel - I don't know if the data is in ES to support this, but overall this page with its filters etc might work driven off ES with facets for Subs/Provider/Platforms on the left - as with the "All Packages" search. Don't know if the work done on the 'spotlight' search might make this approach viable at all.

**Comment by ostephens** [comment] 2015-05-05 09:39
Oh - and @ianibbo has strong feelings about this page :)

**Comment by ostephens** [comment] 2015-05-07 14:44
Note - we also have a request to "Improve search facility on the Institutional Title List" (listed as a "Could Do" in the enhancements list). No further detail on this at the moment but this may back up the idea of a different approach to this than the current one to give us more flexibility with search in the future

**Comment by iyawnis** [comment] 2015-09-23 08:57
@ostephens , do the current search options need to be available on the main screen? For example, would it be acceptable to list all the titles on the main screen, and when a title is clicked it shows details on which subs/plats/providers are related to that specific title?

**Comment by ostephens** [comment] 2015-09-23 11:24
I think institutions probably want to see some basic info on the screen immediately - at least the IE details as currently shown in last col in the current screen.

However I'm not 100% confident about this, and may be worth getting feedback from the community on this if this is challenging (I'm guessing that this is where we hit performance issues?)

**Comment by iyawnis** [comment] 2015-09-23 11:26
Basic info will be available, what we want to do is reduce the amount of filtering applied to the batch of IEs, and instead give the option to apply it on individual titles.

**Comment by ostephens** [comment] 2015-09-23 11:41
Sorry - not sure I understand completely how this would work. Can you provide an illustration or further explanation?

**Comment by iyawnis** [comment] 2015-09-25 11:13
@ostephens  after adding some indexes and reworking the queries the currentTitles screen works fine as it is. I will close this issue as soon as I finish testing. If there are any visual changes that need to be made please create a new issue.

**Closed as completed** 2015-10-07 13:47 UTC
