### ISSUE TITLE
Grails error on ONIX-PL upload

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#558] opened 2013-07-22 21:34 UTC
Tried importing an ONIX-PL using new option in Manage menu - URI http://test.kbplus.ac.uk/kbplus/licenseImport/doImport

Error 500: Internal Server Error
URI
/kbplus/licenseImport/doImport
Class
com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException
Message
Column 'oplt_opl_fk' cannot be null

Trace:

```
Line | Method
```

->>  411 | handleNewInstance     in com.mysql.jdbc.Util

---

|    386 | getInstance           in     ''
|   1041 | createSQLException .  in com.mysql.jdbc.SQLError
|   4187 | checkErrorPacket      in com.mysql.jdbc.MysqlIO
|   4119 | checkErrorPacket . .  in     ''
|   2570 | sendCommand           in     ''
|   2731 | sqlQueryDirect . . .  in     ''
|   2815 | execSQL               in com.mysql.jdbc.ConnectionImpl
|   2155 | executeInternal . . . in com.mysql.jdbc.PreparedStatement
|   2458 | executeUpdate         in     ''
|   2375 | executeUpdate . . . . in     ''
|   2359 | executeUpdate         in     ''
|    105 | executeUpdate . . . . in org.apache.commons.dbcp.DelegatingPreparedStatement
|    273 | doCall                in com.k_int.kbplus.LicenseImportController$_recordOnixplUsageTerm_closure3
|    267 | recordOnixplUsageTerm in com.k_int.kbplus.LicenseImportController
|    204 | doCall                in com.k_int.kbplus.LicenseImportController$_processImport_closure2
|    203 | processImport . . . . in com.k_int.kbplus.LicenseImportController
|     41 | doImport              in     ''
|   1110 | runWorker . . . . . . in java.util.concurrent.ThreadPoolExecutor
|    603 | run                   in java.util.concurrent.ThreadPoolExecutor$Worker
^    722 | run . . . . . . . . . in java.lang.Thread

**Comment by neilmayo** [comment] 2013-07-23 09:02
Hi Owen,

This is the problem I referred to yesterday; Grails won't honour the 
"nullability" of the license property in the ONIX-PL license domain 
class. I changed the code to always create a blank license and have now 
merged it with newdev. I also updated the database table on knowplusdev 
manually to fix it for the moment. It should work now.

Thanks,

Neil

On 22/07/13 22:34, Owen Stephens wrote:

> Tried importing an ONIX-PL using new option in Manage menu - URI 
> http://test.kbplus.ac.uk/kbplus/licenseImport/doImport
> 
> Error 500: Internal Server Error
> URI
> /kbplus/licenseImport/doImport
> Class
> com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException
> Message
> Column 'oplt_opl_fk' cannot be null
> 
> Trace:
> 
> |Line | Method
> |
> 
> ->> 411 | handleNewInstance in com.mysql.jdbc.Util
> 
> ---
> 
> | 386 | getInstance in ''
> | 1041 | createSQLException . in com.mysql.jdbc.SQLError
> | 4187 | checkErrorPacket in com.mysql.jdbc.MysqlIO
> | 4119 | checkErrorPacket . . in ''
> | 2570 | sendCommand in ''
> | 2731 | sqlQueryDirect . . . in ''
> | 2815 | execSQL in com.mysql.jdbc.ConnectionImpl
> | 2155 | executeInternal . . . in com.mysql.jdbc.PreparedStatement
> | 2458 | executeUpdate in ''
> | 2375 | executeUpdate . . . . in ''
> | 2359 | executeUpdate in ''
> | 105 | executeUpdate . . . . in 
> org.apache.commons.dbcp.DelegatingPreparedStatement
> | 273 | doCall in 
> com.k_int.kbplus.LicenseImportController$_recordOnixplUsageTerm_closure3
> | 267 | recordOnixplUsageTerm in com.k_int.kbplus.LicenseImportController
> | 204 | doCall in 
> com.k_int.kbplus.LicenseImportController$_processImport_closure2
> | 203 | processImport . . . . in com.k_int.kbplus.LicenseImportController
> | 41 | doImport in ''
> | 1110 | runWorker . . . . . . in java.util.concurrent.ThreadPoolExecutor
> | 603 | run in java.util.concurrent.ThreadPoolExecutor$Worker
> ^ 722 | run . . . . . . . . . in java.lang.Thread
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/k-int/KBPlus/issues/558.

## 

Neil Mayo
Software Engineer
EDINA (JISC National Data Centre)
University of Edinburgh

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by ianibbo** [comment] 2013-07-23 09:07
Can someone explain the "Honouring the nullability" thing? Doesn't make
sense to me

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by neilmayo** [comment] 2013-07-23 09:13
Sorry. I mean that the OnixplLicense domain class is intended to have an 
optional one-to-one relation to the License class. The license property 
is therefore defined as having a constraint "nullable: true". However 
whichever way I try to define the relationship, Grails will not create 
the table with a nullable column for the license. Therefore I've had to 
ensure there is always a license.

On 23/07/13 10:07, ianibbo wrote:

> Can someone explain the "Honouring the nullability" thing? Doesn't make
> sense to me
> 
> Ian Ibbotson
> Director
> Knowledge Integration Ltd
> 35 Paradise Street, Sheffield. S3 8PZ
> T: 0114 273 8271
> M: 07968 794 630
> W: http://www.k-int.com
> 
> On 23 July 2013 10:02, Neil Mayo notifications@github.com wrote:
> 
> > Hi Owen,
> > 
> > This is the problem I referred to yesterday; Grails won't honour the
> > "nullability" of the license property in the ONIX-PL license domain
> > class. I changed the code to always create a blank license and have now
> > merged it with newdev. I also updated the database table on knowplusdev
> > manually to fix it for the moment. It should work now.
> > 
> > Thanks,
> > 
> > Neil
> > 
> > On 22/07/13 22:34, Owen Stephens wrote:
> > 
> > > Tried importing an ONIX-PL using new option in Manage menu - URI
> > > http://test.kbplus.ac.uk/kbplus/licenseImport/doImport
> > > 
> > > Error 500: Internal Server Error
> > > URI
> > > /kbplus/licenseImport/doImport
> > > Class
> > 
> > com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException
> > 
> > > Message
> > > Column 'oplt_opl_fk' cannot be null
> > > 
> > > Trace:
> > > 
> > > |Line | Method
> > > |
> > > 
> > > ->> 411 | handleNewInstance in com.mysql.jdbc.Util
> > > 
> > > ---
> > > 
> > > | 386 | getInstance in ''
> > > | 1041 | createSQLException . in com.mysql.jdbc.SQLError
> > > | 4187 | checkErrorPacket in com.mysql.jdbc.MysqlIO
> > > | 4119 | checkErrorPacket . . in ''
> > > | 2570 | sendCommand in ''
> > > | 2731 | sqlQueryDirect . . . in ''
> > > | 2815 | execSQL in com.mysql.jdbc.ConnectionImpl
> > > | 2155 | executeInternal . . . in com.mysql.jdbc.PreparedStatement
> > > | 2458 | executeUpdate in ''
> > > | 2375 | executeUpdate . . . . in ''
> > > | 2359 | executeUpdate in ''
> > > | 105 | executeUpdate . . . . in
> > > org.apache.commons.dbcp.DelegatingPreparedStatement
> > > | 273 | doCall in
> > > 
> > > com.k_int.kbplus.LicenseImportController$_recordOnixplUsageTerm_closure3
> > > | 267 | recordOnixplUsageTerm in 
> > > com.k_int.kbplus.LicenseImportController
> > > | 204 | doCall in
> > > com.k_int.kbplus.LicenseImportController$_processImport_closure2
> > > | 203 | processImport . . . . in 
> > > com.k_int.kbplus.LicenseImportController
> > > | 41 | doImport in ''
> > > | 1110 | runWorker . . . . . . in 
> > > java.util.concurrent.ThreadPoolExecutor
> > > | 603 | run in java.util.concurrent.ThreadPoolExecutor$Worker
> > > ^ 722 | run . . . . . . . . . in java.lang.Thread
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/k-int/KBPlus/issues/558.
> > 
> > ## 
> > 
> > Neil Mayo
> > Software Engineer
> > EDINA (JISC National Data Centre)
> > University of Edinburgh
> > 
> > The University of Edinburgh is a charitable body, registered in
> > Scotland, with registration number SC005336.
> > 
> > —
> > Reply to this email directly or view it on 
> > GitHubhttps://github.com/k-int/KBPlus/issues/558#issuecomment-21401577
> > .
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/k-int/KBPlus/issues/558#issuecomment-21401778.

## 

Neil Mayo
Software Engineer
EDINA (JISC National Data Centre)
University of Edinburgh

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by ostephens** [comment] 2013-07-23 09:19
Neil - this sounds like the correct behaviour to me - that is I don't think I can see a scenario where we would want to have an ONIX-PL licence not attached to a KB+ licence?

**Comment by ianibo** [comment] 2013-07-23 09:25
Grails ABSOLUTELY will allow you to have nullable columns. HOWEVER what it
won't do is to make a column nullable that previously wasn't. You'll have
to drop the table and re-create it OR manually remove the not null
constraint.

Have you tried both those things?

On 23 July 2013 10:13, Neil Mayo notifications@github.com wrote:

> Sorry. I mean that the OnixplLicense domain class is intended to have an
> optional one-to-one relation to the License class. The license property
> is therefore defined as having a constraint "nullable: true". However
> whichever way I try to define the relationship, Grails will not create
> the table with a nullable column for the license. Therefore I've had to
> ensure there is always a license.
> 
> On 23/07/13 10:07, ianibbo wrote:
> 
> > Can someone explain the "Honouring the nullability" thing? Doesn't make
> > sense to me
> > 
> > Ian Ibbotson
> > Director
> > Knowledge Integration Ltd
> > 35 Paradise Street, Sheffield. S3 8PZ
> > T: 0114 273 8271
> > M: 07968 794 630
> > W: http://www.k-int.com
> > 
> > On 23 July 2013 10:02, Neil Mayo notifications@github.com wrote:
> > 
> > > Hi Owen,
> > > 
> > > This is the problem I referred to yesterday; Grails won't honour the
> > > "nullability" of the license property in the ONIX-PL license domain
> > > class. I changed the code to always create a blank license and have now
> > > merged it with newdev. I also updated the database table on knowplusdev
> > > manually to fix it for the moment. It should work now.
> > > 
> > > Thanks,
> > > 
> > > Neil
> > > 
> > > On 22/07/13 22:34, Owen Stephens wrote:
> > > 
> > > > Tried importing an ONIX-PL using new option in Manage menu - URI
> > > > http://test.kbplus.ac.uk/kbplus/licenseImport/doImport
> > > > 
> > > > Error 500: Internal Server Error
> > > > URI
> > > > /kbplus/licenseImport/doImport
> > > > Class
> > 
> > com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException
> > 
> > > > Message
> > > > Column 'oplt_opl_fk' cannot be null
> > > > 
> > > > Trace:
> > > > 
> > > > |Line | Method
> > > > |
> > > > 
> > > > ->> 411 | handleNewInstance in com.mysql.jdbc.Util
> > > > 
> > > > ---
> > > > 
> > > > | 386 | getInstance in ''
> > > > | 1041 | createSQLException . in com.mysql.jdbc.SQLError
> > > > | 4187 | checkErrorPacket in com.mysql.jdbc.MysqlIO
> > > > | 4119 | checkErrorPacket . . in ''
> > > > | 2570 | sendCommand in ''
> > > > | 2731 | sqlQueryDirect . . . in ''
> > > > | 2815 | execSQL in com.mysql.jdbc.ConnectionImpl
> > > > | 2155 | executeInternal . . . in com.mysql.jdbc.PreparedStatement
> > > > | 2458 | executeUpdate in ''
> > > > | 2375 | executeUpdate . . . . in ''
> > > > | 2359 | executeUpdate in ''
> > > > | 105 | executeUpdate . . . . in
> > > > org.apache.commons.dbcp.DelegatingPreparedStatement
> > > > | 273 | doCall in
> > > > 
> > > > com.k_int.kbplus.LicenseImportController$_recordOnixplUsageTerm_closure3
> > > > | 267 | recordOnixplUsageTerm in
> > > > com.k_int.kbplus.LicenseImportController
> > > > | 204 | doCall in
> > > > com.k_int.kbplus.LicenseImportController$_processImport_closure2
> > > > | 203 | processImport . . . . in
> > > > com.k_int.kbplus.LicenseImportController
> > > > | 41 | doImport in ''
> > > > | 1110 | runWorker . . . . . . in
> > > > java.util.concurrent.ThreadPoolExecutor
> > > > | 603 | run in java.util.concurrent.ThreadPoolExecutor$Worker
> > > > ^ 722 | run . . . . . . . . . in java.lang.Thread
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub
> > > > https://github.com/k-int/KBPlus/issues/558.
> > > 
> > > ## 
> > > 
> > > Neil Mayo
> > > Software Engineer
> > > EDINA (JISC National Data Centre)
> > > University of Edinburgh
> > > 
> > > The University of Edinburgh is a charitable body, registered in
> > > Scotland, with registration number SC005336.
> > > 
> > > —
> > > Reply to this email directly or view it on
> > > GitHubhttps://github.com/k-int/KBPlus/issues/558#issuecomment-21401577
> > > 
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/k-int/KBPlus/issues/558#issuecomment-21401778.
> 
> ## 
> 
> Neil Mayo
> Software Engineer
> EDINA (JISC National Data Centre)
> University of Edinburgh
> 
> The University of Edinburgh is a charitable body, registered in
> Scotland, with registration number SC005336.
> 
> —
> 
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/558#issuecomment-21402019
> .

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by ianibo** [comment] 2013-07-23 09:26
(Also, as an example, see the owner property on Subscription which is a
nullable FK reference to a license).

On 23 July 2013 10:24, ianibbo@gmail.com ianibbo@gmail.com wrote:

> Grails ABSOLUTELY will allow you to have nullable columns. HOWEVER what it
> won't do is to make a column nullable that previously wasn't. You'll have
> to drop the table and re-create it OR manually remove the not null
> constraint.
> 
> Have you tried both those things?
> 
> On 23 July 2013 10:13, Neil Mayo notifications@github.com wrote:
> 
> > Sorry. I mean that the OnixplLicense domain class is intended to have an
> > optional one-to-one relation to the License class. The license property
> > is therefore defined as having a constraint "nullable: true". However
> > whichever way I try to define the relationship, Grails will not create
> > the table with a nullable column for the license. Therefore I've had to
> > ensure there is always a license.
> > 
> > On 23/07/13 10:07, ianibbo wrote:
> > 
> > > Can someone explain the "Honouring the nullability" thing? Doesn't make
> > > sense to me
> > > 
> > > Ian Ibbotson
> > > Director
> > > Knowledge Integration Ltd
> > > 35 Paradise Street, Sheffield. S3 8PZ
> > > T: 0114 273 8271
> > > M: 07968 794 630
> > > W: http://www.k-int.com
> > > 
> > > On 23 July 2013 10:02, Neil Mayo notifications@github.com wrote:
> > > 
> > > > Hi Owen,
> > > > 
> > > > This is the problem I referred to yesterday; Grails won't honour the
> > > > "nullability" of the license property in the ONIX-PL license domain
> > > > class. I changed the code to always create a blank license and have
> > > > now
> > > > merged it with newdev. I also updated the database table on
> > > > knowplusdev
> > > > manually to fix it for the moment. It should work now.
> > > > 
> > > > Thanks,
> > > > 
> > > > Neil
> > > > 
> > > > On 22/07/13 22:34, Owen Stephens wrote:
> > > > 
> > > > > Tried importing an ONIX-PL using new option in Manage menu - URI
> > > > > http://test.kbplus.ac.uk/kbplus/licenseImport/doImport
> > > > > 
> > > > > Error 500: Internal Server Error
> > > > > URI
> > > > > /kbplus/licenseImport/doImport
> > > > > Class
> > > 
> > > com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException
> > > 
> > > > > Message
> > > > > Column 'oplt_opl_fk' cannot be null
> > > > > 
> > > > > Trace:
> > > > > 
> > > > > |Line | Method
> > > > > |
> > > > > 
> > > > > ->> 411 | handleNewInstance in com.mysql.jdbc.Util
> > > > > 
> > > > > ---
> > > > > 
> > > > > | 386 | getInstance in ''
> > > > > | 1041 | createSQLException . in com.mysql.jdbc.SQLError
> > > > > | 4187 | checkErrorPacket in com.mysql.jdbc.MysqlIO
> > > > > | 4119 | checkErrorPacket . . in ''
> > > > > | 2570 | sendCommand in ''
> > > > > | 2731 | sqlQueryDirect . . . in ''
> > > > > | 2815 | execSQL in com.mysql.jdbc.ConnectionImpl
> > > > > | 2155 | executeInternal . . . in com.mysql.jdbc.PreparedStatement
> > > > > | 2458 | executeUpdate in ''
> > > > > | 2375 | executeUpdate . . . . in ''
> > > > > | 2359 | executeUpdate in ''
> > > > > | 105 | executeUpdate . . . . in
> > > > > org.apache.commons.dbcp.DelegatingPreparedStatement
> > > > > | 273 | doCall in
> > > > > 
> > > > > com.k_int.kbplus.LicenseImportController$_recordOnixplUsageTerm_closure3
> > > > > | 267 | recordOnixplUsageTerm in
> > > > > com.k_int.kbplus.LicenseImportController
> > > > > | 204 | doCall in
> > > > > com.k_int.kbplus.LicenseImportController$_processImport_closure2
> > > > > | 203 | processImport . . . . in
> > > > > com.k_int.kbplus.LicenseImportController
> > > > > | 41 | doImport in ''
> > > > > | 1110 | runWorker . . . . . . in
> > > > > java.util.concurrent.ThreadPoolExecutor
> > > > > | 603 | run in java.util.concurrent.ThreadPoolExecutor$Worker
> > > > > ^ 722 | run . . . . . . . . . in java.lang.Thread
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > https://github.com/k-int/KBPlus/issues/558.
> > > > 
> > > > ## 
> > > > 
> > > > Neil Mayo
> > > > Software Engineer
> > > > EDINA (JISC National Data Centre)
> > > > University of Edinburgh
> > > > 
> > > > The University of Edinburgh is a charitable body, registered in
> > > > Scotland, with registration number SC005336.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on
> > > > GitHub<https://github.com/k-int/KBPlus/issues/558#issuecomment-21401577
> > > > 
> > > > .
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/k-int/KBPlus/issues/558#issuecomment-21401778.
> > 
> > ## 
> > 
> > Neil Mayo
> > Software Engineer
> > EDINA (JISC National Data Centre)
> > University of Edinburgh
> > 
> > The University of Edinburgh is a charitable body, registered in
> > Scotland, with registration number SC005336.
> > 
> > —
> > 
> > Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/558#issuecomment-21402019
> > .
> 
> ## 
> 
> Ian Ibbotson
> W: http://ianibbo.me
> E: ianibbo@gmail.com
> skype: ianibbo
> twitter: ianibbo

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Comment by neilmayo** [comment] 2013-07-23 09:58
I have. I tried several different ways of specifying the link, dropping the table each time before building and restarting, and it did not make any difference. I've manually removed the constraint in the current db but I don't know the best place to initiate this change so it propagates for each new build.

Owen, the idea was that a user may not want to create a matching license at the point of import - that the linking up of ONIX-PL licenses to KB+ licenses might occur at a later stage, considering it is a manual process.

**Comment by ianibbo** [comment] 2013-07-23 10:15
mysql> drop table onixpl_usage_term_license_text;
Query OK, 0 rows affected (0.06 sec)

mysql> drop table onixpl_usage_term;
Query OK, 0 rows affected (0.19 sec)

mysql> drop table onixpl_license_text;
Query OK, 0 rows affected (0.05 sec)

mysql> drop table onixpl_license;
Query OK, 0 rows affected (0.06 sec)

> > > > > grails run-app

mysql> desc onixpl_usage_term;
+-------------------------+------------+------+-----+---------+----------------+
| Field                   | Type       | Null | Key | Default | Extra
   |
+-------------------------+------------+------+-----+---------+----------------+
| oput_id                 | bigint(20) | NO   | PRI | NULL    |
auto_increment |
| oput_version            | bigint(20) | NO   |     | NULL    |
   |
| oput_opl_fk             | bigint(20) | YES  | MUL | NULL    |
   |
| oput_usage_status_rv_fk | bigint(20) | NO   | MUL | NULL    |
   |
| oput_usage_type_rv_fk   | bigint(20) | NO   |     | NULL    |
   |
+-------------------------+------------+------+-----+---------+----------------+
5 rows in set (0.00 sec)

mysql>

Made changes locally, dropped table, re-ran create, seems to work for me
exactly as advertised in documentation.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by neilmayo** [comment] 2013-07-23 10:19
Ian, that's the onixpl_usage_term table - what about the onixpl_license table? Does opl_lic_fk get defined correctly for you?

**Comment by ianibbo** [comment] 2013-07-23 11:12
It doesn't but the same procedure I applied to the usage_term should work..
Provided there isn't an incoming relation from the License table proper
thats defining a 1:1 which implies a mandatory relationship.

I'm quite sure this is something you're doing rather than a problem with
Hibernate tho. Just don't have time to fix it atm.

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

**Comment by ostephens** [comment] 2013-07-23 11:48
Neil - I'm not sure we want a situation where someone is uploading the ONIX-PL licence but not attaching it to a proper KB+ Licence record.

I think originally we discussed having the 'Upload ONIX-PL' option actually accessible via an existing KB+ Licence so that the licence link was also explicit on the upload? Alternatively we could force the specification of an existing KB+ licence at the point of upload?

If we are supporting upload of ONIX-PL independently of a KB+ licence I think it should create a licence. I'm uncomfortable with the idea of ONIX-PL licences floating around independently - I'm worried this increases the risk of creating duplicate licences, and it leads to more complex UI behaviour (i.e. a UI element to allow the user to link an ONIX-PL licence to a KB+ Licence which I think we should try to avoid at this stage.

**Comment by neilmayo** [comment] 2013-07-23 13:24
I assume you have just set nullable to true on the OnixplUsageTerm 
domain class before rebuilding?

I tried this to reproduce your output but I still get a non-nullable 
field. I think it must be because the tables are getting created as 
InnoDB by default and Grails is setting foreign key constraints on them. 
That's the only difference I can see between us. Does "show create table 
onixpl_license" show the creation of an InnoDB or MyISAM table?

On 23/07/13 12:12, ianibbo wrote:

> It doesn't but the same procedure I applied to the usage_term should 
> work..
> Provided there isn't an incoming relation from the License table proper
> thats defining a 1:1 which implies a mandatory relationship.
> 
> I'm quite sure this is something you're doing rather than a problem with
> Hibernate tho. Just don't have time to fix it atm.
> 
> Ian Ibbotson
> Director
> Knowledge Integration Ltd
> 35 Paradise Street, Sheffield. S3 8PZ
> T: 0114 273 8271
> M: 07968 794 630
> W: http://www.k-int.com
> 
> On 23 July 2013 11:19, Neil Mayo notifications@github.com wrote:
> 
> > Ian, that's the onixpl_usage_term table - what about the onixpl_license
> > table? Does opl_lic_fk get defined correctly for you?
> > 
> > —
> > Reply to this email directly or view it on 
> > GitHubhttps://github.com/k-int/KBPlus/issues/558#issuecomment-21405041
> > .
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/k-int/KBPlus/issues/558#issuecomment-21407151.

## 

Neil Mayo
Software Engineer
EDINA (JISC National Data Centre)
University of Edinburgh

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by ianibo** [comment] 2013-07-23 13:26
Actually my local dB is innodb too.. But thats not specified by grails, its
all down to local mysql config.

**Comment by neilmayo** [comment] 2013-07-23 13:55
Owen - this is fine. If the import is only necessary from existing KB+ 
licenses, this simplifies the coding and we can forget about the 
optional relation. It does mean that the import process will be more of 
a hurdle but that's not my problem ;)

## 

To explain what the problem was however, for reference:

The tables were getting created as InnoDB on my machine by default and 
Grails is setting foreign key constraints on them which prevent the 
field being null (or optional).

I tried to force Grails to create MyISAM tables by specifying the 
org.hibernate.dialect.MySQLMyISAMDialect dialect in 
grails-app/conf/DataSource.groovy, but it didn't make any difference. I 
had to specify the dialect in ~/.grails/demo-config.groovy as that 
appears to override environment dataSources defined in the former file.

This time Grails/the dialect produces an SQL statement to create a 
MyISAM table that allows null on the optional field as desired. However 
it turns out that this dialect uses deprecated keyword "TYPE" rather 
than "ENGINE" which has been removed in my version of MySQL (Ver 14.14 
Distrib 5.5.31) so the table creation fails. See 
http://openquery.com/blog/type-disappears-mysql-544.

On 23/07/13 12:48, Owen Stephens wrote:

> Neil - I'm not sure we want a situation where someone is uploading the 
> ONIX-PL licence but not attaching it to a proper KB+ Licence record.
> 
> I think originally we discussed having the 'Upload ONIX-PL' option 
> actually accessible via an existing KB+ Licence so that the licence 
> link was also explicit on the upload? Alternatively we could force the 
> specification of an existing KB+ licence at the point of upload?
> 
> If we are supporting upload of ONIX-PL independently of a KB+ licence 
> I think it should create a licence. I'm uncomfortable with the idea of 
> ONIX-PL licences floating around independently - I'm worried this 
> increases the risk of creating duplicate licences, and it leads to 
> more complex UI behaviour (i.e. a UI element to allow the user to link 
> an ONIX-PL licence to a KB+ Licence which I think we should try to 
> avoid at this stage.
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/k-int/KBPlus/issues/558#issuecomment-21408646.

## 

Neil Mayo
Software Engineer
EDINA (JISC National Data Centre)
University of Edinburgh

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Comment by ostephens** [comment] 2013-07-23 14:07
Thanks Neil. I'd differentiate slightly between the requirement that an ONIX-PL licence has to be linked to a KB+ licence and the import. We could still support (as you suggested earlier) creation of a skeleton KB+ licence on import of the ONIX-PL licence - I can't see anything here that would prevent this behaviour?

However for the moment I'm happy to see us only support import from an existing KB+ licence - this may mean changing where the import option appears in the UI?

**Comment by neilmayo** [comment] 2013-07-23 14:11
Agreed on both counts

On 23/07/13 15:08, Owen Stephens wrote:

> Thanks Neil. I'd differentiate slightly between the requirement that 
> an ONIX-PL licence has to be linked to a KB+ licence and the import. 
> We could still support (as you suggested earlier) creation of a 
> skeleton KB+ licence on import of the ONIX-PL licence - I can't see 
> anything here that would prevent this behaviour?
> 
> However for the moment I'm happy to see us only support import from an 
> existing KB+ licence - this may mean changing where the import option 
> appears in the UI?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/k-int/KBPlus/issues/558#issuecomment-21416273.

## 

Neil Mayo
Software Engineer
EDINA (JISC National Data Centre)
University of Edinburgh

The University of Edinburgh is a charitable body, registered in
Scotland, with registration number SC005336.

**Closed as completed** 2013-07-30 16:16 UTC
