### ISSUE TITLE
Denied access to view a package with 'Public' set to 'yes'

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#508] opened 2013-06-07 10:37 UTC
e.g. tried to view http://knowplusdev.edina.ac.uk/kbplus/packageDetails/show/219 while logged in as 'TestUser1'

Get directed to http://knowplusdev.edina.ac.uk/kbplus/login/denied

This particular package has a Public flag of 'Yes' so should be viewable by all users

**Comment by ianibo** [comment] 2013-06-07 11:21
Duplicate of #508 (Root cause)

On 7 June 2013 11:37, Owen Stephens notifications@github.com wrote:

> e.g. tried to view
> http://knowplusdev.edina.ac.uk/kbplus/packageDetails/show/219 while
> logged in as 'TestUser1'
> 
> Get directed to http://knowplusdev.edina.ac.uk/kbplus/login/denied
> 
> This particular package has a Public flag of 'Yes' so should be viewable
> by all users
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/k-int/KBPlus/issues/508
> .

## 

Ian Ibbotson
W: http://ianibbo.me
E: ianibbo@gmail.com
skype: ianibbo
twitter: ianibbo

**Closed as completed** 2013-06-11 11:17 UTC
