### ISSUE TITLE
Strange behaviour when adding entitlements to specific subscription

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#169] opened 2012-08-11 23:30 UTC
Trying to add entitlements from http://knowplus.edina.ac.uk/kbplus/subscriptionDetails/addEntitlements/243

If I select the first one or two in the list
African Journal of International and Comparative Law
Architectural Heritage

And click 'add entitlements' - they do not get added
If I click any other titles on same screen, works fine

Other subscriptions/add entitlements seem to work OK (or at least not replicated this error on other subs with limited testing)

**Comment by ianibo** [comment] 2012-08-12 08:31
Is there any more detail about the history of this sub? Confirmed the issue on live, but unable to replicate in dev environment... Is there anyting special in the history you can recall?

**Comment by ianibo** [comment] 2012-08-12 09:10
Right.. Looks like the first issue entitlement has it's status set to deleted, but the system is missing a clause to prevent deleted SO IE's from appearing in that screen.

When the IE is copied, it's copied with it's deleted status, which _is_ present on the ST, but because of it's deleted status never appears

What should happen in this case.. Should deleted IE be suppressed in add screen? (Guess so) should deleted IE's have their status resent, (Also users should be prevented from deleting IE's I guess, but this may be a legitimate admin use case so probably something we should figure out)

Phew!

**Comment by ianibo** [comment] 2012-08-12 11:28
Closing this for now. Now Suppresses deleted entitlements from add screen. Pls raise new issue if different behaviour wanted.

**Closed as completed by ianibo** 2012-08-12 11:29 UTC
Labels: bug
