### ISSUE TITLE
Unresponsive Script message in KB+ interface

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#79] opened 2012-07-25 09:40 UTC
Reported separately by two people:
1:
Looking at the "create package" process. Run a search for Wiley, check radio button next to Wiley Online Library Master and hit create subscription. Page takes some time to load and I also get an unresponsive script message: http://knowplus.edina.ac.uk/kbplus/static/plugins/jquery-1.7.1/js/jquery/jquery-1.7.1.min.js:4

2:
When I log into the Subs taken screen in KB+ I keep getting this dalog box appear:
"A script on this page may be busy, or it may have stopped responding...
Script: http://knowplus.edina.ac.uk/kbplus/static/plugins/jquery-1.7.1/js/jquery/jquery-1.7.1.min.js:2"
I think that it is something to do with me trying to edit the Core status of titles.
I am using the most recent version of Firefox

**Comment by ianibbo** [comment] 2012-07-25 09:42
Had a direct message from Liam about this..

Been unable to reproduce so far, same version of firefox.. waiting on liam
for specific OS version information. If you can gather version info from
other case that would be most helpful also

Ian Ibbotson
Director
Knowledge Integration Ltd
35 Paradise Street, Sheffield. S3 8PZ
T: 0114 273 8271
M: 07968 794 630
W: http://www.k-int.com

On Wed, Jul 25, 2012 at 10:40 AM, ostephens <
reply@reply.github.com

**Comment by ostephens** [comment] 2012-07-25 09:54
Will ask

Owen

Owen Stephens
Owen Stephens Consulting
Web: http://www.ostephens.com
Email: owen@ostephens.com
Telephone: 0121 288 6936

**Comment by ianibo** [comment] 2012-07-25 10:03
Done some investigation..

Apparently caused by the click-to-edit code being run to turn all "Click-to-edit" elements into editable components. Each row adds three click-to-edit components. Each component added takes time. Have emailed chirs and robert to ask for advice. Hopefully they won't say "Don't use click to edit" ;)

**Comment by ostephens** [comment] 2012-07-25 10:07
OK - if the answer is not to use click to edit then I'll live!

**Comment by ostephens** [comment] 2012-07-25 14:51
Agreed through email discussion that the solution is to add pagination to the display to avoid performance issues caused by many 'click to edit' elements in a single page

**Comment by ianibo** [comment] 2012-07-30 13:06
This should be resolved by the new pagniation feature as deployed sunday/monday 29/30 jul.

**Closed as completed by ianibo** 2012-07-30 13:06 UTC
