### ISSUE TITLE
Test: Can we test new ISSN-L functionality by loading just a few lines from ISSN-L table

### ISSUE THREAD

**Issue by ostephens** [k-int/KBPlus#1001] opened 2015-08-11 09:59 UTC
As we've established the test server isn't equipped to handle us uploading the full ISSN-L table to test the new ISSN-L functionality, is there any reason we shouldn't upload just a few lines (say for 5 ISSNs) of the table to check the funcitonality?

**Comment by ostephens** [comment] 2015-08-17 12:39
Tried uploaded a test tsv file containing col headings + two lines:

ISSN    ISSN-L
1548-5943   1548-5943
1548-5951   1548-5943

Got Grails error:

Error 500: Internal Server Error
URI
/test/admin/uploadIssnL
Class
org.hibernate.LazyInitializationException
Message
could not initialize proxy - no Session

Trace
    Line | Method
->>  198 | doFilter  in /layouts/mmbootstrap.gsp

---

|    176 | doFilter  in     ''
|   1142 | runWorker in     ''
|    617 | run       in     ''
^    745 | run . . . in     ''

Caused by GroovyPagesException: Error processing GroovyPageView: Error executing tag <g:render>: Error executing tag <r:script>: could not initialize proxy - no Session
->>  530 | doFilter  in /layouts/mmbootstrap.gsp

---

Caused by GrailsTagException: Error executing tag <g:render>: Error executing tag <r:script>: could not initialize proxy - no Session
->>  398 | doCall    in /WEB-INF/grails-app/views/layouts/mmbootstrap.gsp

---

Caused by GrailsTagException: Error executing tag <r:script>: could not initialize proxy - no Session
->>   27 | run       in /WEB-INF/grails-app/views/layouts/_analytics.gsp

---

Caused by LazyInitializationException: could not initialize proxy - no Session
->>   26 | doCall    in gsp_demo_layouts_analytics_gsp$_run_closure1

---

|    455 | doCall    in org.grails.plugin.resource.ResourceTagLib$_closure7
|     33 | run . . . in gsp_demo_layouts_analytics_gsp
|    559 | doCall    in gsp_demo_layoutsmmbootstrap_gsp$_run_closure2
|    573 | run . . . in gsp_demo_layoutsmmbootstrap_gsp
|    198 | doFilter  in net.bull.javamelody.MonitoringFilter
|    176 | doFilter  in     ''
|   1142 | runWorker in java.util.concurrent.ThreadPoolExecutor
|    617 | run . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    745 | run       in java.lang.Thread

**Comment by ianibo** [comment] 2015-08-17 12:58
There were commits for this work not on test - have merged dev-integration into test now - difficult to know what features belong in what branch at the moment. May have unexpected side effects. Testing now.

**Comment by ianibo** [comment] 2015-08-18 17:26
Caused by the call to cleanUpGorm flushing the user object, but that object being referred to in the layout - specifically analytics code to add user and institution into request. Moved user selection to end of controller method.

**Comment by iyawnis** [comment] 2015-08-20 15:56
This looks wrapped up.

**Closed as completed by iyawnis** 2015-08-20 15:56 UTC
Labels: question
